sym16_simple_stock_homepage:
    path:     /home/{name}
    defaults: { _controller: SYM16SimpleStockBundle:Default:index }

sym16_simple_stock_ilike:
    path: /iLike/{verbe}
    defaults: { _controller: SYM16SimpleStockBundle:BARYPremierControleur:iLike}

sym16_simple_stock_produit:
    path: /produit/{chiffre1}/{chiffre2}
    defaults: { _controller: SYM16SimpleStockBundle:BARYPremierControleur:produit}


sym16_simple_stock_racine:
    path: /racine/{valeur}/{radical}
    defaults: { _controller: SYM16SimpleStockBundle:BARYPremierControleur:racine}

sym16_simple_stock_lister: 
    path: /lister 
    defaults: { _controller: SYM16SimpleStockBundle:BARYPremierControleur:lister} 

sym16_simple_stock_supprimer: 
    path: /supprimer 
    defaults: { _controller: SYM16SimpleStockBundle:BARYPremierControleur:supprimer} 

sym16_simple_stock_modifier: 
    path: /modifier 
    defaults: { _controller: SYM16SimpleStockBundle:BARYPremierControleur:modifier}
